### PR TITLE
ci: automatic release workflow

### LINKED ISSUE #92: Automatic release workflow
**Describe the solution you'd like**
A one-click release workflow that automatically compiles change logs from the PRs since the last release

**Additional context**
Implementation similar to that in [amltk](https://github.com/automl/amltk)

### PR DESCRIPTION
**Pull request by timurcarstensen**
Adds an automatic release workflow

Changes: 
- adding `commitizen` as a development dependency
- adding `commitizen` as a pre-commit hook
- adding `pr-conventional-commits.yml`: a GH action to check whether the PR title conforms to conventional commits

TODOs: 
- [x] tagged releases / commits (not sure yet?)
- [x] Release workflow with publishing to PyPI (follow `amltk` setup)
- [x] Optional: enforce signed commits

Closes #92

### CODE REVIEW

**Comment by timurcarstensen** [comment]
@aaronkl What do you think about adding branch protection rules to enforce signed commits to `main`?

**Comment by aaronkl** [comment]
@timurcarstensen thanks for taking care of this .  Do you mean to make sure that people do not directly push to the main branch without sending a PR first? Do we need signed commits for that? Or would a simple branch protection rule be enough?

**Comment by timurcarstensen** [comment]
> @timurcarstensen thanks for taking care of this . Do you mean to make sure that people do not directly push to the main branch without sending a PR first? Do we need signed commits for that? Or would a simple branch protection rule be enough?

I just set up a branch protection rule s.t. we must always create a PR (which we enforce to be squash-merged). This sort-of already enforces signed commits on main since squash-merged PRs through the GitHub web UI will automatically be signed. We could also enforce signed commits everywhere (e.g., also dev branches) but that seems somewhat unnecessary for our application

**Comment by aaronkl** [comment]
ok great. I agree that enforcing it everywhere would be overkill

**Pull request merged**
